new test in actions for evaluating v3 test coverage (#197)

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -35,7 +35,25 @@ jobs:
         go-version-file: "go.mod"
 
     - name: Run Unit Tests
-      run: go test -v ./...
+      run: |
+          go test ./... -coverprofile cover.out
+
+    - name: Quality Gate - V3 test coverage above threshold
+      env:
+        TESTCOVERAGE_THRESHOLD: 70
+      run: |
+          go test github.com/smartcontractkit/ocr2keepers/pkg/v3/... -coverprofile coverV3.out -covermode count
+          echo "Quality Gate: checking V3 test coverage is above threshold ..."
+          echo "Threshold              : $TESTCOVERAGE_THRESHOLD %"
+          totalCoverage=`go tool cover -func=coverV3.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+          echo "Current test coverage  : $totalCoverage %"
+          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+            echo "V3 test coverage OK"
+          else
+            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+            echo "Failed"
+            exit 1
+          fi
 
   race-test:
     runs-on: ubuntu-latest
