added separate check for internal package with higher threshold

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -37,9 +37,40 @@ jobs:
         go test -v ./... -coverprofile cover.out -covermode count
         go tool cover -func cover.out
 
-    - name: Code Coverage Threshold Check
+    - name: Total Code Coverage Threshold Check
       env:
         TESTCOVERAGE_THRESHOLD: 50
+      run: |
+        echo "Code Coverage Threshold Check: coverage should be above threshold"
+        echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+        totalCoverage=`go tool cover -func=cover.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+        echo "Current test coverage : $totalCoverage %"
+        if (( $(echo "totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+          echo "OK"
+        else
+          echo "Current test coverage is below threshold."
+          echo "Check failed"
+          exit 1
+        fi
+
+  internal-unit-test:
+    name: Internal Package Coverage Check
+    runs-on: ubuntu-latest
+    needs: [ lint ]
+    steps:
+    - uses: actions/checkout@v3
+    - uses: actions/setup-go@v3
+      with:
+        go-version: 1.19
+
+    - name: Run Unit Tests
+      run: |
+        go test -v ./internal/... -coverprofile cover.out -covermode count
+        go tool cover -func cover.out
+
+    - name: Internal Package Code Coverage Threshold Check
+      env:
+        TESTCOVERAGE_THRESHOLD: 80
       run: |
         echo "Code Coverage Threshold Check: coverage should be above threshold"
         echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
